dataopsvalley_dbt:
  outputs:
    TestDockerK8:
      type: bigquery
      #method: service-account
      method: oauth
      project: project-dataopsvalley-test  # name of the project in BigQuery
      dataset: dbt_dwh_ds
      threads: 1
      impersonate_service_account: dbt-user@project-dataopsvalley-test.iam.gserviceaccount.com
      fixed_retries: 1
      location: me-west1
      priority: interactive
      timeout_seconds: 300

    TestAuth:
      type: bigquery
      method: oauth
      project: project-dataopsvalley-test
      location: me-west1
      dataset: dbt_dwh_ds # You can also use "schema" here
      threads: 1
  target: TestDockerK8
