select
    id,
    immigrationYear,
    originCountry,
    translationAssistance,
    language,
    economicHardship,
    detail,
    employment,
    workplace,
    halat,
    sachir_union_for_graph,
    activeBusiness,
    detailActive,
    getToBusiness,
    atzmai_union_for_graph,
    appliedBefore,
    appliedAnswer,
    applied_union_for_graph,
    referenceNumber,
    sentDateTime,
    sentDate,

from {{ ref('stg_evc_ironswords_absorption_and_immigration_roots') }}
